export type LayoutStructure = 
  | 'single-column' 
  | 'left-sidebar' 
  | 'right-sidebar' 
  | 'top-banner' 
  | 'timeline' 
  | 'minimal-ats'
  | 'full-height-sidebar';

export type FontTheme = 'sans' | 'serif' | 'mono';

export type StyleCategory = 
  | 'Executive'
  | 'Tech & Engineering'
  | 'Creative & Design'
  | 'ATS Minimal'
  | 'Medical & Academic'
  | 'Modern Startup'
  | 'Legal & Finance';

export interface CVStyle {
  id: string;
  number: number;
  name: string;
  category: StyleCategory;
  description: string;
  layout: LayoutStructure;
  font: FontTheme;
  colors: {
    headerBg: string;
    headerText: string;
    headerJob: string;
    headerContact: string;
    sectionTitle: string;
    sectionLine: string;
    tagBg: string;
    tagBorder: string;
    tagText: string;
    cardBorder: string;
    sidebarBg?: string;
    sidebarBorder?: string;
    accentDot?: string;
    previewHex: string;
  };
}

// 100 Curated, Production-Ready, Distinct CV Styles
export const CV_STYLES: CVStyle[] = [
  // 1-3: The Original Core Classics
  {
    id: 'blue',
    number: 1,
    name: 'Professional Blue',
    category: 'Executive',
    description: 'Clean corporate deep navy with crisp contrast and structured sections.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-blue-950 via-blue-900 to-indigo-900',
      headerText: 'text-white',
      headerJob: 'text-blue-200',
      headerContact: 'text-blue-100',
      sectionTitle: 'text-blue-950 border-blue-600',
      sectionLine: 'border-b-2 border-blue-600',
      tagBg: 'bg-blue-50/80',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-900',
      cardBorder: 'border-slate-200',
      previewHex: '#1e3a8a',
    }
  },
  {
    id: 'black',
    number: 2,
    name: 'Classic Black',
    category: 'ATS Minimal',
    description: 'Timeless monochrome editorial layout tailored for ATS bots and recruiters.',
    layout: 'minimal-ats',
    font: 'serif',
    colors: {
      headerBg: 'bg-stone-950',
      headerText: 'text-stone-100',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-950 border-stone-900',
      sectionLine: 'border-b border-stone-900',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-900',
      cardBorder: 'border-stone-300',
      previewHex: '#0c0a09',
    }
  },
  {
    id: 'green',
    number: 3,
    name: 'Modern Green',
    category: 'Modern Startup',
    description: 'Emerald and forest green modern layout with soft sage tags and badges.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-emerald-950 via-emerald-900 to-teal-900',
      headerText: 'text-white',
      headerJob: 'text-emerald-200',
      headerContact: 'text-emerald-100',
      sectionTitle: 'text-emerald-900 border-emerald-600',
      sectionLine: 'border-b-2 border-emerald-600',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-900',
      cardBorder: 'border-emerald-100',
      sidebarBg: 'bg-emerald-50/40',
      sidebarBorder: 'border-emerald-100',
      previewHex: '#065f46',
    }
  },
  // 4-15: Executive & Corporate Excellence
  {
    id: 'executive-slate',
    number: 4,
    name: 'Executive Slate',
    category: 'Executive',
    description: 'High-level C-suite template with refined slate tones and clean divider bars.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-900',
      headerText: 'text-white',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-200',
      sectionTitle: 'text-slate-900 border-slate-700',
      sectionLine: 'border-b-2 border-slate-700',
      tagBg: 'bg-slate-100',
      tagBorder: 'border-slate-300',
      tagText: 'text-slate-900',
      cardBorder: 'border-slate-200',
      previewHex: '#0f172a',
    }
  },
  {
    id: 'oxford-navy',
    number: 5,
    name: 'Oxford Navy',
    category: 'Executive',
    description: 'Prestigious academic and executive navy styling with subtle warm gold accents.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-sky-950',
      headerText: 'text-amber-50',
      headerJob: 'text-amber-200',
      headerContact: 'text-sky-100',
      sectionTitle: 'text-sky-950 border-amber-600',
      sectionLine: 'border-b-2 border-amber-600',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-sky-100',
      previewHex: '#082f49',
    }
  },
  {
    id: 'boardroom-charcoal',
    number: 6,
    name: 'Boardroom Charcoal',
    category: 'Executive',
    description: 'Understated matte charcoal tone suited for directors and senior managers.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-neutral-900',
      headerText: 'text-white',
      headerJob: 'text-neutral-300',
      headerContact: 'text-neutral-300',
      sectionTitle: 'text-neutral-900 border-neutral-800',
      sectionLine: 'border-b-2 border-neutral-800',
      tagBg: 'bg-neutral-100',
      tagBorder: 'border-neutral-300',
      tagText: 'text-neutral-800',
      cardBorder: 'border-neutral-300',
      accentDot: 'bg-neutral-800',
      previewHex: '#171717',
    }
  },
  {
    id: 'sapphire-prestige',
    number: 7,
    name: 'Sapphire Prestige',
    category: 'Executive',
    description: 'Vibrant sapphire blue header with high-contrast text and two-column layout.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-blue-800',
      headerText: 'text-white',
      headerJob: 'text-blue-100',
      headerContact: 'text-blue-50',
      sectionTitle: 'text-blue-900 border-blue-700',
      sectionLine: 'border-b-2 border-blue-700',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-900',
      cardBorder: 'border-blue-100',
      sidebarBg: 'bg-blue-50/30',
      sidebarBorder: 'border-blue-100',
      previewHex: '#1d4ed8',
    }
  },
  {
    id: 'regal-crimson',
    number: 8,
    name: 'Regal Crimson',
    category: 'Executive',
    description: 'Distinguished deep crimson and mahogany for prominent leaders.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-rose-950',
      headerText: 'text-white',
      headerJob: 'text-rose-200',
      headerContact: 'text-rose-100',
      sectionTitle: 'text-rose-950 border-rose-700',
      sectionLine: 'border-b-2 border-rose-700',
      tagBg: 'bg-rose-50',
      tagBorder: 'border-rose-200',
      tagText: 'text-rose-900',
      cardBorder: 'border-rose-100',
      previewHex: '#4c0519',
    }
  },
  {
    id: 'monarch-indigo',
    number: 9,
    name: 'Monarch Indigo',
    category: 'Executive',
    description: 'Deep royal indigo with structured sidebar and sharp contact cards.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-indigo-950',
      headerText: 'text-white',
      headerJob: 'text-indigo-200',
      headerContact: 'text-indigo-100',
      sectionTitle: 'text-indigo-950 border-indigo-600',
      sectionLine: 'border-b-2 border-indigo-600',
      tagBg: 'bg-indigo-50',
      tagBorder: 'border-indigo-200',
      tagText: 'text-indigo-950',
      cardBorder: 'border-indigo-100',
      sidebarBg: 'bg-indigo-50/30',
      sidebarBorder: 'border-indigo-100',
      previewHex: '#1e1b4b',
    }
  },
  {
    id: 'titanium-silver',
    number: 10,
    name: 'Titanium Silver',
    category: 'Executive',
    description: 'Ultra-modern metallic silver and deep zinc theme for industrial leaders.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-zinc-800',
      headerText: 'text-zinc-50',
      headerJob: 'text-zinc-300',
      headerContact: 'text-zinc-300',
      sectionTitle: 'text-zinc-900 border-zinc-500',
      sectionLine: 'border-b-2 border-zinc-500',
      tagBg: 'bg-zinc-100',
      tagBorder: 'border-zinc-300',
      tagText: 'text-zinc-800',
      cardBorder: 'border-zinc-200',
      previewHex: '#27272a',
    }
  },
  {
    id: 'diplomat-forest',
    number: 11,
    name: 'Diplomat Forest',
    category: 'Executive',
    description: 'Stately dark forest tone with understated elegance and formal typography.',
    layout: 'timeline',
    font: 'serif',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-emerald-50',
      headerJob: 'text-emerald-200',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-emerald-950 border-emerald-800',
      sectionLine: 'border-b-2 border-emerald-800',
      tagBg: 'bg-emerald-50/70',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-950',
      cardBorder: 'border-stone-200',
      accentDot: 'bg-emerald-800',
      previewHex: '#022c22',
    }
  },
  {
    id: 'mariner-deep-sea',
    number: 12,
    name: 'Mariner Deep Sea',
    category: 'Executive',
    description: 'Oceanic blue-green palette engineered for operations and logistics heads.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-cyan-950',
      headerText: 'text-cyan-50',
      headerJob: 'text-cyan-200',
      headerContact: 'text-cyan-100',
      sectionTitle: 'text-cyan-950 border-cyan-700',
      sectionLine: 'border-b-2 border-cyan-700',
      tagBg: 'bg-cyan-50',
      tagBorder: 'border-cyan-200',
      tagText: 'text-cyan-900',
      cardBorder: 'border-cyan-100',
      previewHex: '#083344',
    }
  },
  {
    id: 'crown-amethyst',
    number: 13,
    name: 'Crown Amethyst',
    category: 'Executive',
    description: 'Rich dark violet with regal poise for arts, media, and corporate executives.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-purple-950',
      headerText: 'text-purple-50',
      headerJob: 'text-purple-200',
      headerContact: 'text-purple-100',
      sectionTitle: 'text-purple-950 border-purple-600',
      sectionLine: 'border-b-2 border-purple-600',
      tagBg: 'bg-purple-50',
      tagBorder: 'border-purple-200',
      tagText: 'text-purple-950',
      cardBorder: 'border-purple-100',
      sidebarBg: 'bg-purple-50/30',
      sidebarBorder: 'border-purple-100',
      previewHex: '#3b0764',
    }
  },
  {
    id: 'consortium-bronze',
    number: 14,
    name: 'Consortium Bronze',
    category: 'Executive',
    description: 'Warm metallic bronze and dark chocolate tones with refined balance.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-amber-950',
      headerText: 'text-amber-50',
      headerJob: 'text-amber-200',
      headerContact: 'text-amber-100',
      sectionTitle: 'text-amber-950 border-amber-700',
      sectionLine: 'border-b-2 border-amber-700',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-900',
      cardBorder: 'border-amber-100',
      previewHex: '#451a03',
    }
  },
  {
    id: 'sovereign-graphite',
    number: 15,
    name: 'Sovereign Graphite',
    category: 'Executive',
    description: 'Pure graphite and white with razor-sharp editorial spacing.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-white',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-stone-800',
      sectionLine: 'border-b-2 border-stone-800',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      sidebarBg: 'bg-stone-50',
      sidebarBorder: 'border-stone-200',
      previewHex: '#1c1917',
    }
  },
  // 16-30: Tech & Engineering Powerhouses
  {
    id: 'cyber-terminal',
    number: 16,
    name: 'Cyber Terminal',
    category: 'Tech & Engineering',
    description: 'Monospace hacker-inspired dark terminal header with phosphor green accents.',
    layout: 'single-column',
    font: 'mono',
    colors: {
      headerBg: 'bg-black',
      headerText: 'text-emerald-400 font-mono',
      headerJob: 'text-emerald-300 font-mono',
      headerContact: 'text-stone-300 font-mono',
      sectionTitle: 'text-emerald-900 border-emerald-500 font-mono',
      sectionLine: 'border-b-2 border-emerald-500',
      tagBg: 'bg-emerald-950/20 font-mono',
      tagBorder: 'border-emerald-300',
      tagText: 'text-emerald-900',
      cardBorder: 'border-emerald-200',
      previewHex: '#10b981',
    }
  },
  {
    id: 'silicon-valley',
    number: 17,
    name: 'Silicon Valley',
    category: 'Tech & Engineering',
    description: 'Clean modern tech blue with high readability and optimized skill chips.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-blue-600',
      headerText: 'text-white',
      headerJob: 'text-blue-100',
      headerContact: 'text-blue-50',
      sectionTitle: 'text-blue-700 border-blue-500',
      sectionLine: 'border-b-2 border-blue-500',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-700',
      cardBorder: 'border-blue-100',
      sidebarBg: 'bg-slate-50',
      sidebarBorder: 'border-slate-200',
      previewHex: '#2563eb',
    }
  },
  {
    id: 'devops-matrix',
    number: 18,
    name: 'DevOps Matrix',
    category: 'Tech & Engineering',
    description: 'Dark slate and cyan tech layout built for cloud architects and SREs.',
    layout: 'top-banner',
    font: 'mono',
    colors: {
      headerBg: 'bg-slate-950',
      headerText: 'text-cyan-400',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-900 border-cyan-500',
      sectionLine: 'border-b-2 border-cyan-500',
      tagBg: 'bg-cyan-50',
      tagBorder: 'border-cyan-300',
      tagText: 'text-cyan-900',
      cardBorder: 'border-slate-200',
      previewHex: '#06b6d4',
    }
  },
  {
    id: 'fullstack-cobalt',
    number: 19,
    name: 'Fullstack Cobalt',
    category: 'Tech & Engineering',
    description: 'Electric cobalt header with structured timeline for software engineers.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-blue-700',
      headerText: 'text-white',
      headerJob: 'text-blue-100',
      headerContact: 'text-blue-100',
      sectionTitle: 'text-blue-900 border-blue-600',
      sectionLine: 'border-b-2 border-blue-600',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-800',
      cardBorder: 'border-blue-100',
      accentDot: 'bg-blue-600',
      previewHex: '#1d4ed8',
    }
  },
  {
    id: 'ai-neural',
    number: 20,
    name: 'AI Neural',
    category: 'Tech & Engineering',
    description: 'Violet-indigo gradient with modern typography for data scientists and ML engineers.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-violet-900 via-indigo-900 to-purple-900',
      headerText: 'text-white',
      headerJob: 'text-violet-200',
      headerContact: 'text-violet-100',
      sectionTitle: 'text-violet-900 border-violet-500',
      sectionLine: 'border-b-2 border-violet-500',
      tagBg: 'bg-violet-50',
      tagBorder: 'border-violet-200',
      tagText: 'text-violet-900',
      cardBorder: 'border-violet-100',
      sidebarBg: 'bg-violet-50/20',
      sidebarBorder: 'border-violet-100',
      previewHex: '#7c3aed',
    }
  },
  {
    id: 'civil-blueprint',
    number: 21,
    name: 'Civil Blueprint',
    category: 'Tech & Engineering',
    description: 'Deep blueprint blue with technical precision and crisp architectural dividers.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-sky-900',
      headerText: 'text-white',
      headerJob: 'text-sky-200',
      headerContact: 'text-sky-100',
      sectionTitle: 'text-sky-950 border-sky-600',
      sectionLine: 'border-b-2 border-sky-600',
      tagBg: 'bg-sky-50',
      tagBorder: 'border-sky-300',
      tagText: 'text-sky-950',
      cardBorder: 'border-sky-200',
      previewHex: '#0369a1',
    }
  },
  {
    id: 'robotics-amber',
    number: 22,
    name: 'Robotics Amber',
    category: 'Tech & Engineering',
    description: 'Industrial charcoal with hazard amber accents for mechatronics & hardware pros.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-neutral-900',
      headerText: 'text-white',
      headerJob: 'text-amber-400',
      headerContact: 'text-neutral-300',
      sectionTitle: 'text-neutral-900 border-amber-500',
      sectionLine: 'border-b-2 border-amber-500',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-300',
      tagText: 'text-amber-900',
      cardBorder: 'border-neutral-200',
      sidebarBg: 'bg-neutral-50',
      sidebarBorder: 'border-neutral-200',
      previewHex: '#f59e0b',
    }
  },
  {
    id: 'cloud-azure',
    number: 23,
    name: 'Cloud Azure',
    category: 'Tech & Engineering',
    description: 'Azure sky gradient with lightweight modern icons and tags.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-blue-600 to-sky-600',
      headerText: 'text-white',
      headerJob: 'text-sky-100',
      headerContact: 'text-sky-50',
      sectionTitle: 'text-blue-900 border-sky-500',
      sectionLine: 'border-b-2 border-sky-500',
      tagBg: 'bg-sky-50',
      tagBorder: 'border-sky-200',
      tagText: 'text-blue-900',
      cardBorder: 'border-sky-100',
      previewHex: '#0284c7',
    }
  },
  {
    id: 'kernel-dark',
    number: 24,
    name: 'Kernel Dark',
    category: 'Tech & Engineering',
    description: 'Low-level systems engineer layout with dark accents and mono highlights.',
    layout: 'single-column',
    font: 'mono',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-stone-100',
      headerJob: 'text-stone-400',
      headerContact: 'text-stone-400',
      sectionTitle: 'text-stone-900 border-stone-600',
      sectionLine: 'border-b-2 border-stone-600',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      previewHex: '#44403c',
    }
  },
  {
    id: 'telecom-teal',
    number: 25,
    name: 'Telecom Teal',
    category: 'Tech & Engineering',
    description: 'Deep teal and aqua designed for networks and telecommunications engineers.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-teal-900',
      headerText: 'text-white',
      headerJob: 'text-teal-200',
      headerContact: 'text-teal-100',
      sectionTitle: 'text-teal-950 border-teal-600',
      sectionLine: 'border-b-2 border-teal-600',
      tagBg: 'bg-teal-50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-900',
      cardBorder: 'border-teal-100',
      accentDot: 'bg-teal-600',
      previewHex: '#0f766e',
    }
  },
  {
    id: 'crypto-solidity',
    number: 26,
    name: 'Crypto Solidity',
    category: 'Tech & Engineering',
    description: 'Dark purple-slate with geometric headers for Web3 and blockchain developers.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-900',
      headerText: 'text-purple-300',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-400',
      sectionTitle: 'text-purple-950 border-purple-500',
      sectionLine: 'border-b-2 border-purple-500',
      tagBg: 'bg-purple-50',
      tagBorder: 'border-purple-200',
      tagText: 'text-purple-900',
      cardBorder: 'border-slate-200',
      sidebarBg: 'bg-slate-50',
      sidebarBorder: 'border-slate-200',
      previewHex: '#6366f1',
    }
  },
  {
    id: 'qa-emerald',
    number: 27,
    name: 'QA Emerald',
    category: 'Tech & Engineering',
    description: 'Clean mint and emerald theme symbolizing test passes and reliability.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-emerald-800',
      headerText: 'text-white',
      headerJob: 'text-emerald-100',
      headerContact: 'text-emerald-50',
      sectionTitle: 'text-emerald-900 border-emerald-600',
      sectionLine: 'border-b-2 border-emerald-600',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-900',
      cardBorder: 'border-emerald-100',
      previewHex: '#059669',
    }
  },
  {
    id: 'embedded-copper',
    number: 28,
    name: 'Embedded Copper',
    category: 'Tech & Engineering',
    description: 'Warm copper PCB tone for electrical, firmware, and electronics engineers.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-amber-900',
      headerText: 'text-amber-50',
      headerJob: 'text-amber-200',
      headerContact: 'text-amber-100',
      sectionTitle: 'text-amber-950 border-amber-600',
      sectionLine: 'border-b-2 border-amber-600',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-300',
      tagText: 'text-amber-950',
      cardBorder: 'border-amber-100',
      previewHex: '#78350f',
    }
  },
  {
    id: 'cybersecurity-red',
    number: 29,
    name: 'Cybersecurity Red',
    category: 'Tech & Engineering',
    description: 'Black and alert crimson designed for red team, security analysts, and SOC pros.',
    layout: 'timeline',
    font: 'mono',
    colors: {
      headerBg: 'bg-stone-950',
      headerText: 'text-red-400 font-mono',
      headerJob: 'text-stone-300 font-mono',
      headerContact: 'text-stone-400 font-mono',
      sectionTitle: 'text-stone-900 border-red-600 font-mono',
      sectionLine: 'border-b-2 border-red-600',
      tagBg: 'bg-red-50',
      tagBorder: 'border-red-200',
      tagText: 'text-red-900',
      cardBorder: 'border-stone-200',
      accentDot: 'bg-red-600',
      previewHex: '#dc2626',
    }
  },
  {
    id: 'scrum-indigo',
    number: 30,
    name: 'Scrum Indigo',
    category: 'Tech & Engineering',
    description: 'Agile and product engineering layout with well-balanced sidebar and clean badges.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-indigo-800',
      headerText: 'text-white',
      headerJob: 'text-indigo-200',
      headerContact: 'text-indigo-100',
      sectionTitle: 'text-indigo-900 border-indigo-600',
      sectionLine: 'border-b-2 border-indigo-600',
      tagBg: 'bg-indigo-50',
      tagBorder: 'border-indigo-200',
      tagText: 'text-indigo-900',
      cardBorder: 'border-indigo-100',
      sidebarBg: 'bg-indigo-50/40',
      sidebarBorder: 'border-indigo-100',
      previewHex: '#4338ca',
    }
  },
  // 31-45: Creative & Design Portfolios
  {
    id: 'creative-coral',
    number: 31,
    name: 'Creative Coral',
    category: 'Creative & Design',
    description: 'Warm coral and peach tones for UI/UX designers, illustrators, and art directors.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-rose-500 to-orange-500',
      headerText: 'text-white',
      headerJob: 'text-rose-100',
      headerContact: 'text-rose-50',
      sectionTitle: 'text-rose-900 border-rose-400',
      sectionLine: 'border-b-2 border-rose-400',
      tagBg: 'bg-rose-50',
      tagBorder: 'border-rose-200',
      tagText: 'text-rose-800',
      cardBorder: 'border-rose-100',
      sidebarBg: 'bg-orange-50/30',
      sidebarBorder: 'border-orange-100',
      previewHex: '#f43f5e',
    }
  },
  {
    id: 'nordic-minimal',
    number: 32,
    name: 'Nordic Minimal',
    category: 'Creative & Design',
    description: 'Scandinavian airy white with charcoal typography and generous whitespace.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-stone-100',
      headerText: 'text-stone-900',
      headerJob: 'text-stone-600',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-stone-900 border-stone-300',
      sectionLine: 'border-b border-stone-300',
      tagBg: 'bg-stone-50',
      tagBorder: 'border-stone-200',
      tagText: 'text-stone-700',
      cardBorder: 'border-stone-200',
      previewHex: '#78716c',
    }
  },
  {
    id: 'bauhaus-primary',
    number: 33,
    name: 'Bauhaus Primary',
    category: 'Creative & Design',
    description: 'Artistic primary accents inspired by modernism and the Bauhaus school.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-neutral-900',
      headerText: 'text-yellow-400',
      headerJob: 'text-neutral-200',
      headerContact: 'text-neutral-300',
      sectionTitle: 'text-neutral-900 border-red-500',
      sectionLine: 'border-b-2 border-red-500',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-300',
      tagText: 'text-blue-900',
      cardBorder: 'border-neutral-300',
      sidebarBg: 'bg-neutral-50',
      sidebarBorder: 'border-neutral-200',
      previewHex: '#eab308',
    }
  },
  {
    id: 'editorial-vogue',
    number: 34,
    name: 'Editorial Vogue',
    category: 'Creative & Design',
    description: 'High-fashion editorial serif with centered masthead and delicate dividing rules.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-stone-50',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-stone-400',
      sectionLine: 'border-b border-stone-400',
      tagBg: 'bg-stone-50',
      tagBorder: 'border-stone-200',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      previewHex: '#292524',
    }
  },
  {
    id: 'terracotta-earth',
    number: 35,
    name: 'Terracotta Earth',
    category: 'Creative & Design',
    description: 'Warm clay terracotta with organic Mediterranean warmth.',
    layout: 'left-sidebar',
    font: 'serif',
    colors: {
      headerBg: 'bg-orange-900',
      headerText: 'text-orange-50',
      headerJob: 'text-orange-200',
      headerContact: 'text-orange-100',
      sectionTitle: 'text-orange-950 border-orange-600',
      sectionLine: 'border-b-2 border-orange-600',
      tagBg: 'bg-orange-50',
      tagBorder: 'border-orange-200',
      tagText: 'text-orange-900',
      cardBorder: 'border-orange-100',
      sidebarBg: 'bg-orange-50/40',
      sidebarBorder: 'border-orange-100',
      previewHex: '#9a3412',
    }
  },
  {
    id: 'tokyo-neon',
    number: 36,
    name: 'Tokyo Neon',
    category: 'Creative & Design',
    description: 'Deep midnight navy with magenta and electric violet accents.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-950',
      headerText: 'text-fuchsia-400',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-400',
      sectionTitle: 'text-slate-900 border-fuchsia-500',
      sectionLine: 'border-b-2 border-fuchsia-500',
      tagBg: 'bg-fuchsia-50',
      tagBorder: 'border-fuchsia-200',
      tagText: 'text-fuchsia-900',
      cardBorder: 'border-slate-200',
      accentDot: 'bg-fuchsia-600',
      previewHex: '#d946ef',
    }
  },
  {
    id: 'studio-lavender',
    number: 37,
    name: 'Studio Lavender',
    category: 'Creative & Design',
    description: 'Gentle lavender and soft violet palette for content creators and marketers.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-purple-800',
      headerText: 'text-white',
      headerJob: 'text-purple-200',
      headerContact: 'text-purple-100',
      sectionTitle: 'text-purple-900 border-purple-400',
      sectionLine: 'border-b-2 border-purple-400',
      tagBg: 'bg-purple-50',
      tagBorder: 'border-purple-200',
      tagText: 'text-purple-900',
      cardBorder: 'border-purple-100',
      previewHex: '#9333ea',
    }
  },
  {
    id: 'golden-hour',
    number: 38,
    name: 'Golden Hour',
    category: 'Creative & Design',
    description: 'Warm sunset amber with honey accents for photographers and video producers.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-amber-600 to-orange-600',
      headerText: 'text-white',
      headerJob: 'text-amber-100',
      headerContact: 'text-amber-50',
      sectionTitle: 'text-amber-950 border-amber-500',
      sectionLine: 'border-b-2 border-amber-500',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-900',
      cardBorder: 'border-amber-100',
      previewHex: '#d97706',
    }
  },
  {
    id: 'mint-matcha',
    number: 39,
    name: 'Mint Matcha',
    category: 'Creative & Design',
    description: 'Refreshing pastel mint and deep sage for wellness and lifestyle creatives.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-teal-800',
      headerText: 'text-teal-50',
      headerJob: 'text-teal-200',
      headerContact: 'text-teal-100',
      sectionTitle: 'text-teal-900 border-teal-500',
      sectionLine: 'border-b-2 border-teal-500',
      tagBg: 'bg-teal-50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-800',
      cardBorder: 'border-teal-100',
      sidebarBg: 'bg-teal-50/30',
      sidebarBorder: 'border-teal-100',
      previewHex: '#14b8a6',
    }
  },
  {
    id: 'monochrome-bold',
    number: 40,
    name: 'Monochrome Bold',
    category: 'Creative & Design',
    description: 'High-contrast black blocks and heavy typography for bold copywriters.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-black',
      headerText: 'text-white',
      headerJob: 'text-neutral-400',
      headerContact: 'text-neutral-300',
      sectionTitle: 'text-black border-black',
      sectionLine: 'border-b-2 border-black',
      tagBg: 'bg-neutral-100',
      tagBorder: 'border-black',
      tagText: 'text-black',
      cardBorder: 'border-black',
      sidebarBg: 'bg-neutral-50',
      sidebarBorder: 'border-neutral-200',
      previewHex: '#000000',
    }
  },
  {
    id: 'sakura-blossom',
    number: 41,
    name: 'Sakura Blossom',
    category: 'Creative & Design',
    description: 'Soft pink and plum floral notes with gentle, refined visual balance.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-rose-900',
      headerText: 'text-rose-50',
      headerJob: 'text-rose-200',
      headerContact: 'text-rose-100',
      sectionTitle: 'text-rose-950 border-rose-400',
      sectionLine: 'border-b-2 border-rose-400',
      tagBg: 'bg-rose-50',
      tagBorder: 'border-rose-200',
      tagText: 'text-rose-900',
      cardBorder: 'border-rose-100',
      previewHex: '#be123c',
    }
  },
  {
    id: 'coastal-driftwood',
    number: 42,
    name: 'Coastal Driftwood',
    category: 'Creative & Design',
    description: 'Muted slate and sea glass green inspired by coastal landscapes.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-800',
      headerText: 'text-teal-100',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-900 border-teal-600',
      sectionLine: 'border-b-2 border-teal-600',
      tagBg: 'bg-teal-50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-900',
      cardBorder: 'border-slate-200',
      accentDot: 'bg-teal-600',
      previewHex: '#475569',
    }
  },
  {
    id: 'industrial-loft',
    number: 43,
    name: 'Industrial Loft',
    category: 'Creative & Design',
    description: 'Exposed dark zinc with raw geometric lines for interior architects.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-zinc-900',
      headerText: 'text-white',
      headerJob: 'text-orange-400',
      headerContact: 'text-zinc-300',
      sectionTitle: 'text-zinc-900 border-orange-500',
      sectionLine: 'border-b-2 border-orange-500',
      tagBg: 'bg-orange-50',
      tagBorder: 'border-orange-200',
      tagText: 'text-orange-950',
      cardBorder: 'border-zinc-200',
      previewHex: '#3f3f46',
    }
  },
  {
    id: 'cyberpunk-magenta',
    number: 44,
    name: 'Cyberpunk Magenta',
    category: 'Creative & Design',
    description: 'Futuristic dark purple and hot magenta accents for game developers.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-indigo-950',
      headerText: 'text-pink-400',
      headerJob: 'text-indigo-200',
      headerContact: 'text-indigo-200',
      sectionTitle: 'text-indigo-950 border-pink-500',
      sectionLine: 'border-b-2 border-pink-500',
      tagBg: 'bg-pink-50',
      tagBorder: 'border-pink-200',
      tagText: 'text-pink-900',
      cardBorder: 'border-indigo-100',
      sidebarBg: 'bg-indigo-50/20',
      sidebarBorder: 'border-indigo-100',
      previewHex: '#ec4899',
    }
  },
  {
    id: 'artisan-leather',
    number: 45,
    name: 'Artisan Leather',
    category: 'Creative & Design',
    description: 'Rich saddle brown and sepia tones for traditional craftsmanship & luxury.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-amber-950',
      headerText: 'text-amber-100',
      headerJob: 'text-amber-300',
      headerContact: 'text-amber-200',
      sectionTitle: 'text-amber-950 border-amber-800',
      sectionLine: 'border-b-2 border-amber-800',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-900',
      cardBorder: 'border-amber-100',
      previewHex: '#713f12',
    }
  },
  // 46-60: ATS Minimalist & Clean
  {
    id: 'ats-pure-white',
    number: 46,
    name: 'ATS Pure White',
    category: 'ATS Minimal',
    description: 'Zero clutter, standard fonts, pure white background for 99.9% ATS pass rate.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-white border-b-2 border-black',
      headerText: 'text-black',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-black border-black',
      sectionLine: 'border-b border-black',
      tagBg: 'bg-transparent',
      tagBorder: 'border-stone-400',
      tagText: 'text-stone-900',
      cardBorder: 'border-stone-300',
      previewHex: '#ffffff',
    }
  },
  {
    id: 'ats-harvard-standard',
    number: 47,
    name: 'Harvard Standard',
    category: 'ATS Minimal',
    description: 'The iconic Ivy League serif template with centered header and horizontal rules.',
    layout: 'minimal-ats',
    font: 'serif',
    colors: {
      headerBg: 'bg-white border-b border-stone-900',
      headerText: 'text-stone-950',
      headerJob: 'text-stone-800',
      headerContact: 'text-stone-700',
      sectionTitle: 'text-stone-950 border-stone-800',
      sectionLine: 'border-b border-stone-800',
      tagBg: 'bg-stone-50',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-900',
      cardBorder: 'border-stone-200',
      previewHex: '#1c1917',
    }
  },
  {
    id: 'ats-navy-accent',
    number: 48,
    name: 'ATS Navy Accent',
    category: 'ATS Minimal',
    description: 'Standard parsing structure with a single tasteful navy rule under section titles.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-white border-b border-blue-900',
      headerText: 'text-blue-950',
      headerJob: 'text-blue-900',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-blue-950 border-blue-900',
      sectionLine: 'border-b border-blue-900',
      tagBg: 'bg-blue-50/50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-950',
      cardBorder: 'border-stone-200',
      previewHex: '#1e3a8a',
    }
  },
  {
    id: 'ats-slate-compact',
    number: 49,
    name: 'ATS Slate Compact',
    category: 'ATS Minimal',
    description: 'High information density layout designed to fit extensive experience onto 1 page.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-100 border-b border-slate-300',
      headerText: 'text-slate-900',
      headerJob: 'text-slate-700',
      headerContact: 'text-slate-600',
      sectionTitle: 'text-slate-900 border-slate-400',
      sectionLine: 'border-b border-slate-400',
      tagBg: 'bg-slate-50',
      tagBorder: 'border-slate-300',
      tagText: 'text-slate-800',
      cardBorder: 'border-slate-200',
      previewHex: '#334155',
    }
  },
  {
    id: 'ats-oxford-rules',
    number: 50,
    name: 'ATS Oxford Rules',
    category: 'ATS Minimal',
    description: 'Double hairline borders separating major sections for prestigious clarity.',
    layout: 'minimal-ats',
    font: 'serif',
    colors: {
      headerBg: 'bg-white border-b-2 border-double border-stone-800',
      headerText: 'text-stone-900',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-stone-900 border-stone-700',
      sectionLine: 'border-b-2 border-double border-stone-700',
      tagBg: 'bg-stone-50',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-300',
      previewHex: '#292524',
    }
  },
  {
    id: 'ats-charcoal-mono',
    number: 51,
    name: 'ATS Charcoal Mono',
    category: 'ATS Minimal',
    description: 'Clean monospaced headers with sans serif body for technical resumes.',
    layout: 'minimal-ats',
    font: 'mono',
    colors: {
      headerBg: 'bg-stone-50 border-b border-stone-400',
      headerText: 'text-stone-900',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-stone-900 border-stone-600',
      sectionLine: 'border-b border-stone-600',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      previewHex: '#57534e',
    }
  },
  {
    id: 'ats-forest-subtle',
    number: 52,
    name: 'ATS Forest Subtle',
    category: 'ATS Minimal',
    description: 'Subtle dark forest headers with 100% standard ATS parsable body hierarchy.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-white border-b border-emerald-900',
      headerText: 'text-emerald-950',
      headerJob: 'text-emerald-900',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-emerald-950 border-emerald-800',
      sectionLine: 'border-b border-emerald-800',
      tagBg: 'bg-emerald-50/40',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-950',
      cardBorder: 'border-stone-200',
      previewHex: '#064e3b',
    }
  },
  {
    id: 'ats-burgundy-rule',
    number: 53,
    name: 'ATS Burgundy Rule',
    category: 'ATS Minimal',
    description: 'Classy wine-colored hairline accents for business analysts and consultants.',
    layout: 'minimal-ats',
    font: 'serif',
    colors: {
      headerBg: 'bg-white border-b border-rose-900',
      headerText: 'text-rose-950',
      headerJob: 'text-rose-900',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-rose-950 border-rose-800',
      sectionLine: 'border-b border-rose-800',
      tagBg: 'bg-rose-50/50',
      tagBorder: 'border-rose-200',
      tagText: 'text-rose-950',
      cardBorder: 'border-stone-200',
      previewHex: '#881337',
    }
  },
  {
    id: 'ats-graphite-grid',
    number: 54,
    name: 'ATS Graphite Grid',
    category: 'ATS Minimal',
    description: 'Clean typographic grid optimized for machine scanning and fast screening.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-stone-50 border-b border-stone-300',
      headerText: 'text-stone-900',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-stone-900 border-stone-400',
      sectionLine: 'border-b border-stone-400',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      previewHex: '#44403c',
    }
  },
  {
    id: 'ats-indigo-simple',
    number: 55,
    name: 'ATS Indigo Simple',
    category: 'ATS Minimal',
    description: 'Uncomplicated structure with crisp indigo text highlights.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-white border-b border-indigo-900',
      headerText: 'text-indigo-950',
      headerJob: 'text-indigo-800',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-indigo-950 border-indigo-700',
      sectionLine: 'border-b border-indigo-700',
      tagBg: 'bg-indigo-50/50',
      tagBorder: 'border-indigo-200',
      tagText: 'text-indigo-900',
      cardBorder: 'border-stone-200',
      previewHex: '#3730a3',
    }
  },
  {
    id: 'ats-mono-classic',
    number: 56,
    name: 'ATS Mono Classic',
    category: 'ATS Minimal',
    description: 'Pure typewriter-like aesthetic popular with UNIX administrators and security auditors.',
    layout: 'minimal-ats',
    font: 'mono',
    colors: {
      headerBg: 'bg-white border-b border-black',
      headerText: 'text-black',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-black border-black',
      sectionLine: 'border-b border-black',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-black',
      cardBorder: 'border-stone-300',
      previewHex: '#000000',
    }
  },
  {
    id: 'ats-steel-border',
    number: 57,
    name: 'ATS Steel Border',
    category: 'ATS Minimal',
    description: 'Cool metallic steel divider lines that render cleanly on any monochrome printer.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-white border-b border-slate-700',
      headerText: 'text-slate-900',
      headerJob: 'text-slate-700',
      headerContact: 'text-slate-600',
      sectionTitle: 'text-slate-900 border-slate-500',
      sectionLine: 'border-b border-slate-500',
      tagBg: 'bg-slate-50',
      tagBorder: 'border-slate-200',
      tagText: 'text-slate-800',
      cardBorder: 'border-slate-200',
      previewHex: '#64748b',
    }
  },
  {
    id: 'ats-cambridge-clean',
    number: 58,
    name: 'Cambridge Clean',
    category: 'ATS Minimal',
    description: 'Conservative British academic styling with classic serif and small-caps.',
    layout: 'minimal-ats',
    font: 'serif',
    colors: {
      headerBg: 'bg-white border-b border-stone-800',
      headerText: 'text-stone-900',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-stone-900 border-stone-600',
      sectionLine: 'border-b border-stone-600',
      tagBg: 'bg-stone-50',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      previewHex: '#1c1917',
    }
  },
  {
    id: 'ats-teal-breeze',
    number: 59,
    name: 'ATS Teal Breeze',
    category: 'ATS Minimal',
    description: 'Airy layout with subtle oceanic dividers, ideal for medical and non-profit roles.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-white border-b border-teal-800',
      headerText: 'text-teal-950',
      headerJob: 'text-teal-800',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-teal-950 border-teal-700',
      sectionLine: 'border-b border-teal-700',
      tagBg: 'bg-teal-50/50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-950',
      cardBorder: 'border-stone-200',
      previewHex: '#115e59',
    }
  },
  {
    id: 'ats-warm-stone',
    number: 60,
    name: 'ATS Warm Stone',
    category: 'ATS Minimal',
    description: 'Warm cream and stone hues providing a softer look without sacrificing readability.',
    layout: 'minimal-ats',
    font: 'sans',
    colors: {
      headerBg: 'bg-amber-50/60 border-b border-amber-200',
      headerText: 'text-stone-900',
      headerJob: 'text-stone-700',
      headerContact: 'text-stone-600',
      sectionTitle: 'text-stone-900 border-stone-400',
      sectionLine: 'border-b border-stone-400',
      tagBg: 'bg-white',
      tagBorder: 'border-amber-200',
      tagText: 'text-stone-800',
      cardBorder: 'border-amber-100',
      previewHex: '#fef3c7',
    }
  },
  // 61-70: Medical & Academic
  {
    id: 'clinical-white',
    number: 61,
    name: 'Clinical White',
    category: 'Medical & Academic',
    description: 'Ultra-hygienic cyan and white layout for physicians, surgeons, and nurses.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-sky-800',
      headerText: 'text-white',
      headerJob: 'text-sky-100',
      headerContact: 'text-sky-50',
      sectionTitle: 'text-sky-950 border-sky-600',
      sectionLine: 'border-b-2 border-sky-600',
      tagBg: 'bg-sky-50',
      tagBorder: 'border-sky-200',
      tagText: 'text-sky-900',
      cardBorder: 'border-sky-100',
      previewHex: '#0284c7',
    }
  },
  {
    id: 'academic-fellow',
    number: 62,
    name: 'Academic Fellow',
    category: 'Medical & Academic',
    description: 'Formal serif designed for university professors, researchers, and PhD candidates.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-amber-100',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-amber-700',
      sectionLine: 'border-b-2 border-amber-700',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-stone-200',
      previewHex: '#292524',
    }
  },
  {
    id: 'biotech-emerald',
    number: 63,
    name: 'Biotech Emerald',
    category: 'Medical & Academic',
    description: 'Clean sage and emerald theme for life sciences and pharmaceutical researchers.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-emerald-900',
      headerText: 'text-emerald-50',
      headerJob: 'text-emerald-200',
      headerContact: 'text-emerald-100',
      sectionTitle: 'text-emerald-950 border-emerald-600',
      sectionLine: 'border-b-2 border-emerald-600',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-900',
      cardBorder: 'border-emerald-100',
      sidebarBg: 'bg-emerald-50/30',
      sidebarBorder: 'border-emerald-100',
      previewHex: '#065f46',
    }
  },
  {
    id: 'surgical-blue',
    number: 64,
    name: 'Surgical Blue',
    category: 'Medical & Academic',
    description: 'Standard medical scrub blue with crisp white headers and credential badges.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-cyan-800',
      headerText: 'text-white',
      headerJob: 'text-cyan-100',
      headerContact: 'text-cyan-50',
      sectionTitle: 'text-cyan-950 border-cyan-600',
      sectionLine: 'border-b-2 border-cyan-600',
      tagBg: 'bg-cyan-50',
      tagBorder: 'border-cyan-200',
      tagText: 'text-cyan-900',
      cardBorder: 'border-cyan-100',
      accentDot: 'bg-cyan-600',
      previewHex: '#0891b2',
    }
  },
  {
    id: 'research-scholar',
    number: 65,
    name: 'Research Scholar',
    category: 'Medical & Academic',
    description: 'Detailed two-column layout highlighting publications, credentials, and honors.',
    layout: 'right-sidebar',
    font: 'serif',
    colors: {
      headerBg: 'bg-indigo-950',
      headerText: 'text-indigo-50',
      headerJob: 'text-indigo-200',
      headerContact: 'text-indigo-100',
      sectionTitle: 'text-indigo-950 border-indigo-700',
      sectionLine: 'border-b-2 border-indigo-700',
      tagBg: 'bg-indigo-50',
      tagBorder: 'border-indigo-200',
      tagText: 'text-indigo-950',
      cardBorder: 'border-indigo-100',
      sidebarBg: 'bg-indigo-50/20',
      sidebarBorder: 'border-indigo-100',
      previewHex: '#312e81',
    }
  },
  {
    id: 'pediatric-warmth',
    number: 66,
    name: 'Pediatric Care',
    category: 'Medical & Academic',
    description: 'Gentle warmth with sky blue and soft amber accents for pediatric specialists.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-sky-700',
      headerText: 'text-white',
      headerJob: 'text-amber-200',
      headerContact: 'text-sky-100',
      sectionTitle: 'text-sky-900 border-amber-400',
      sectionLine: 'border-b-2 border-amber-400',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-900',
      cardBorder: 'border-sky-100',
      sidebarBg: 'bg-sky-50/40',
      sidebarBorder: 'border-sky-100',
      previewHex: '#0369a1',
    }
  },
  {
    id: 'pharma-violet',
    number: 67,
    name: 'Pharma Violet',
    category: 'Medical & Academic',
    description: 'Modern chemical and laboratory violet layout for pharmacist & toxicologist CVs.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-purple-900',
      headerText: 'text-white',
      headerJob: 'text-purple-200',
      headerContact: 'text-purple-100',
      sectionTitle: 'text-purple-950 border-purple-600',
      sectionLine: 'border-b-2 border-purple-600',
      tagBg: 'bg-purple-50',
      tagBorder: 'border-purple-200',
      tagText: 'text-purple-900',
      cardBorder: 'border-purple-100',
      previewHex: '#581c87',
    }
  },
  {
    id: 'dental-frost',
    number: 68,
    name: 'Dental Frost',
    category: 'Medical & Academic',
    description: 'Sparkling clean cyan and soft silver styling for dentists & orthodontists.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-teal-700',
      headerText: 'text-white',
      headerJob: 'text-teal-100',
      headerContact: 'text-teal-50',
      sectionTitle: 'text-teal-900 border-teal-500',
      sectionLine: 'border-b-2 border-teal-500',
      tagBg: 'bg-teal-50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-900',
      cardBorder: 'border-teal-100',
      previewHex: '#0f766e',
    }
  },
  {
    id: 'genetics-dna',
    number: 69,
    name: 'Genetics Helix',
    category: 'Medical & Academic',
    description: 'Deep navy and mint accents highlighting technical laboratory competencies.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-900',
      headerText: 'text-emerald-300',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-950 border-emerald-500',
      sectionLine: 'border-b-2 border-emerald-500',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-900',
      cardBorder: 'border-slate-200',
      accentDot: 'bg-emerald-500',
      previewHex: '#10b981',
    }
  },
  {
    id: 'oxford-dean',
    number: 70,
    name: 'Dean Emeritus',
    category: 'Medical & Academic',
    description: 'Classic crimson and gold traditional European academic hierarchy.',
    layout: 'minimal-ats',
    font: 'serif',
    colors: {
      headerBg: 'bg-red-950 border-b border-amber-500',
      headerText: 'text-amber-100',
      headerJob: 'text-amber-200',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-red-950 border-amber-600',
      sectionLine: 'border-b-2 border-amber-600',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-stone-200',
      previewHex: '#7f1d1d',
    }
  },
  // 71-85: Modern Startup & Growth
  {
    id: 'unicorn-gradient',
    number: 71,
    name: 'Unicorn Gradient',
    category: 'Modern Startup',
    description: 'Vibrant indigo-to-fuchsia gradient header tailored for hyper-growth innovators.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600',
      headerText: 'text-white',
      headerJob: 'text-purple-100',
      headerContact: 'text-purple-50',
      sectionTitle: 'text-purple-900 border-purple-500',
      sectionLine: 'border-b-2 border-purple-500',
      tagBg: 'bg-purple-50',
      tagBorder: 'border-purple-200',
      tagText: 'text-purple-900',
      cardBorder: 'border-purple-100',
      sidebarBg: 'bg-purple-50/20',
      sidebarBorder: 'border-purple-100',
      previewHex: '#8b5cf6',
    }
  },
  {
    id: 'fintech-mint',
    number: 72,
    name: 'FinTech Mint',
    category: 'Modern Startup',
    description: 'Sharp dark slate with fresh mint accents for payment & banking innovators.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-900',
      headerText: 'text-white',
      headerJob: 'text-emerald-400',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-950 border-emerald-500',
      sectionLine: 'border-b-2 border-emerald-500',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-950',
      cardBorder: 'border-slate-200',
      previewHex: '#059669',
    }
  },
  {
    id: 'saas-electric',
    number: 73,
    name: 'SaaS Electric',
    category: 'Modern Startup',
    description: 'Electric blue and cyan designed for B2B SaaS product managers & founders.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-blue-600',
      headerText: 'text-white',
      headerJob: 'text-cyan-200',
      headerContact: 'text-blue-100',
      sectionTitle: 'text-blue-900 border-cyan-500',
      sectionLine: 'border-b-2 border-cyan-500',
      tagBg: 'bg-cyan-50',
      tagBorder: 'border-cyan-200',
      tagText: 'text-blue-900',
      cardBorder: 'border-blue-100',
      previewHex: '#2563eb',
    }
  },
  {
    id: 'product-lead',
    number: 74,
    name: 'Product Lead',
    category: 'Modern Startup',
    description: 'Structured two-column layout highlighting OKRs, KPIs, and metric wins.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-amber-400',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-amber-500',
      sectionLine: 'border-b-2 border-amber-500',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-stone-200',
      sidebarBg: 'bg-stone-50',
      sidebarBorder: 'border-stone-200',
      previewHex: '#f59e0b',
    }
  },
  {
    id: 'growth-hacker',
    number: 75,
    name: 'Growth Hacker',
    category: 'Modern Startup',
    description: 'High-energy lime green and jet black for viral marketers and UA leads.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-black',
      headerText: 'text-lime-400',
      headerJob: 'text-neutral-300',
      headerContact: 'text-neutral-400',
      sectionTitle: 'text-neutral-900 border-lime-500',
      sectionLine: 'border-b-2 border-lime-500',
      tagBg: 'bg-lime-50',
      tagBorder: 'border-lime-300',
      tagText: 'text-lime-950',
      cardBorder: 'border-neutral-200',
      accentDot: 'bg-lime-500',
      previewHex: '#84cc16',
    }
  },
  {
    id: 'vc-pitch',
    number: 76,
    name: 'Venture Capital',
    category: 'Modern Startup',
    description: 'Refined deep navy and champagne gold designed for venture associates.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-slate-950',
      headerText: 'text-amber-100',
      headerJob: 'text-amber-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-950 border-amber-500',
      sectionLine: 'border-b-2 border-amber-500',
      tagBg: 'bg-amber-50/70',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-slate-200',
      previewHex: '#020617',
    }
  },
  {
    id: 'creator-orange',
    number: 77,
    name: 'Creator Studio',
    category: 'Modern Startup',
    description: 'Vibrant blood orange with bold headlines for media founders & influencers.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-orange-600',
      headerText: 'text-white',
      headerJob: 'text-orange-100',
      headerContact: 'text-orange-50',
      sectionTitle: 'text-orange-950 border-orange-500',
      sectionLine: 'border-b-2 border-orange-500',
      tagBg: 'bg-orange-50',
      tagBorder: 'border-orange-200',
      tagText: 'text-orange-900',
      cardBorder: 'border-orange-100',
      sidebarBg: 'bg-orange-50/40',
      sidebarBorder: 'border-orange-100',
      previewHex: '#ea580c',
    }
  },
  {
    id: 'ai-startup-teal',
    number: 78,
    name: 'GenAI Venture',
    category: 'Modern Startup',
    description: 'Teal and cyber cyan styling representing next-gen generative AI applications.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-teal-950',
      headerText: 'text-teal-300',
      headerJob: 'text-teal-100',
      headerContact: 'text-teal-200',
      sectionTitle: 'text-teal-950 border-teal-500',
      sectionLine: 'border-b-2 border-teal-500',
      tagBg: 'bg-teal-50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-950',
      cardBorder: 'border-teal-100',
      previewHex: '#14b8a6',
    }
  },
  {
    id: 'remote-first',
    number: 79,
    name: 'Remote First',
    category: 'Modern Startup',
    description: 'Airy sky blue layout with timezone and remote collaboration highlights.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-sky-800',
      headerText: 'text-white',
      headerJob: 'text-sky-200',
      headerContact: 'text-sky-100',
      sectionTitle: 'text-sky-950 border-sky-500',
      sectionLine: 'border-b-2 border-sky-500',
      tagBg: 'bg-sky-50',
      tagBorder: 'border-sky-200',
      tagText: 'text-sky-900',
      cardBorder: 'border-sky-100',
      previewHex: '#0284c7',
    }
  },
  {
    id: 'community-builder',
    number: 80,
    name: 'Community Lead',
    category: 'Modern Startup',
    description: 'Warm purple and coral palette for developer relations and community managers.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-purple-700 to-rose-600',
      headerText: 'text-white',
      headerJob: 'text-purple-100',
      headerContact: 'text-purple-50',
      sectionTitle: 'text-purple-950 border-rose-500',
      sectionLine: 'border-b-2 border-rose-500',
      tagBg: 'bg-purple-50',
      tagBorder: 'border-purple-200',
      tagText: 'text-purple-900',
      cardBorder: 'border-purple-100',
      sidebarBg: 'bg-purple-50/20',
      sidebarBorder: 'border-purple-100',
      previewHex: '#7e22ce',
    }
  },
  {
    id: 'ecommerce-shopify',
    number: 81,
    name: 'E-Commerce DTC',
    category: 'Modern Startup',
    description: 'Deep forest green and soft gold for direct-to-consumer digital commerce heads.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-emerald-950',
      headerText: 'text-emerald-100',
      headerJob: 'text-emerald-300',
      headerContact: 'text-emerald-200',
      sectionTitle: 'text-emerald-950 border-emerald-600',
      sectionLine: 'border-b-2 border-emerald-600',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-950',
      cardBorder: 'border-emerald-100',
      accentDot: 'bg-emerald-600',
      previewHex: '#064e3b',
    }
  },
  {
    id: 'crypto-nomad',
    number: 82,
    name: 'Digital Nomad',
    category: 'Modern Startup',
    description: 'Sunset gradient with compact layout for nomadic builders across Bali, Dubai, Lisbon.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-gradient-to-r from-amber-500 to-rose-600',
      headerText: 'text-white',
      headerJob: 'text-amber-100',
      headerContact: 'text-amber-50',
      sectionTitle: 'text-stone-900 border-rose-500',
      sectionLine: 'border-b-2 border-rose-500',
      tagBg: 'bg-rose-50',
      tagBorder: 'border-rose-200',
      tagText: 'text-rose-900',
      cardBorder: 'border-stone-200',
      previewHex: '#f43f5e',
    }
  },
  {
    id: 'agile-coach',
    number: 83,
    name: 'Agile Coach',
    category: 'Modern Startup',
    description: 'Clean teal and cobalt sidebar layout for Scrum Masters and transformation leads.',
    layout: 'right-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-teal-900',
      headerText: 'text-white',
      headerJob: 'text-teal-200',
      headerContact: 'text-teal-100',
      sectionTitle: 'text-teal-950 border-teal-600',
      sectionLine: 'border-b-2 border-teal-600',
      tagBg: 'bg-teal-50',
      tagBorder: 'border-teal-200',
      tagText: 'text-teal-900',
      cardBorder: 'border-teal-100',
      sidebarBg: 'bg-teal-50/40',
      sidebarBorder: 'border-teal-100',
      previewHex: '#0f766e',
    }
  },
  {
    id: 'stealth-founder',
    number: 84,
    name: 'Stealth Founder',
    category: 'Modern Startup',
    description: 'Minimalist obsidian and charcoal with punchy bullet highlights for serial entrepreneurs.',
    layout: 'single-column',
    font: 'sans',
    colors: {
      headerBg: 'bg-stone-950',
      headerText: 'text-white',
      headerJob: 'text-stone-400',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-stone-800',
      sectionLine: 'border-b-2 border-stone-800',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-800',
      cardBorder: 'border-stone-200',
      previewHex: '#0c0a09',
    }
  },
  {
    id: 'scaleup-operations',
    number: 85,
    name: 'ScaleUp Ops',
    category: 'Modern Startup',
    description: 'Electric blue and royal indigo for Chief of Staff and Operations heads.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-blue-900',
      headerText: 'text-white',
      headerJob: 'text-blue-200',
      headerContact: 'text-blue-100',
      sectionTitle: 'text-blue-950 border-blue-600',
      sectionLine: 'border-b-2 border-blue-600',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-900',
      cardBorder: 'border-blue-100',
      sidebarBg: 'bg-blue-50/30',
      sidebarBorder: 'border-blue-100',
      previewHex: '#1e3a8a',
    }
  },
  // 86-100: Legal, Finance & Banking
  {
    id: 'wall-street',
    number: 86,
    name: 'Wall Street',
    category: 'Legal & Finance',
    description: 'Conservative pinstripe dark slate with authoritative monetary tone.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-slate-950',
      headerText: 'text-slate-50',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-950 border-slate-700',
      sectionLine: 'border-b-2 border-slate-700',
      tagBg: 'bg-slate-100',
      tagBorder: 'border-slate-300',
      tagText: 'text-slate-900',
      cardBorder: 'border-slate-200',
      previewHex: '#020617',
    }
  },
  {
    id: 'private-equity',
    number: 87,
    name: 'Private Equity',
    category: 'Legal & Finance',
    description: 'Subdued deep navy with discreet champagne accents for buyout partners.',
    layout: 'top-banner',
    font: 'serif',
    colors: {
      headerBg: 'bg-blue-950',
      headerText: 'text-amber-100',
      headerJob: 'text-amber-200',
      headerContact: 'text-blue-100',
      sectionTitle: 'text-blue-950 border-amber-600',
      sectionLine: 'border-b-2 border-amber-600',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-blue-100',
      previewHex: '#172554',
    }
  },
  {
    id: 'jurist-barrister',
    number: 88,
    name: 'Senior Barrister',
    category: 'Legal & Finance',
    description: 'Traditional British courtroom layout with classic serif and double rules.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-stone-100',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-stone-800',
      sectionLine: 'border-b border-stone-800',
      tagBg: 'bg-stone-50',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-900',
      cardBorder: 'border-stone-300',
      previewHex: '#1c1917',
    }
  },
  {
    id: 'mergers-acquisitions',
    number: 89,
    name: 'M&A Advisory',
    category: 'Legal & Finance',
    description: 'Crisp corporate layout highlighting transaction volume and deal summaries.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-900',
      headerText: 'text-white',
      headerJob: 'text-blue-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-950 border-blue-600',
      sectionLine: 'border-b-2 border-blue-600',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-950',
      cardBorder: 'border-slate-200',
      sidebarBg: 'bg-slate-50',
      sidebarBorder: 'border-slate-200',
      previewHex: '#1e293b',
    }
  },
  {
    id: 'swiss-banking',
    number: 90,
    name: 'Swiss Private Bank',
    category: 'Legal & Finance',
    description: 'Impeccable alpine restraint with dark chocolate and crisp ivory tones.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-amber-950',
      headerText: 'text-amber-50',
      headerJob: 'text-amber-200',
      headerContact: 'text-amber-100',
      sectionTitle: 'text-amber-950 border-amber-800',
      sectionLine: 'border-b-2 border-amber-800',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-900',
      cardBorder: 'border-amber-100',
      previewHex: '#451a03',
    }
  },
  {
    id: 'cpa-auditor',
    number: 91,
    name: 'Chartered CPA',
    category: 'Legal & Finance',
    description: 'Clean numeric-friendly grid for public accountants and forensic auditors.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-emerald-950',
      headerText: 'text-white',
      headerJob: 'text-emerald-200',
      headerContact: 'text-emerald-100',
      sectionTitle: 'text-emerald-950 border-emerald-700',
      sectionLine: 'border-b-2 border-emerald-700',
      tagBg: 'bg-emerald-50',
      tagBorder: 'border-emerald-200',
      tagText: 'text-emerald-950',
      cardBorder: 'border-emerald-100',
      accentDot: 'bg-emerald-700',
      previewHex: '#022c22',
    }
  },
  {
    id: 'general-counsel',
    number: 92,
    name: 'General Counsel',
    category: 'Legal & Finance',
    description: 'Corporate legal officer template with authoritative burgundy & bronze touches.',
    layout: 'right-sidebar',
    font: 'serif',
    colors: {
      headerBg: 'bg-rose-950',
      headerText: 'text-rose-50',
      headerJob: 'text-rose-200',
      headerContact: 'text-rose-100',
      sectionTitle: 'text-rose-950 border-rose-700',
      sectionLine: 'border-b-2 border-rose-700',
      tagBg: 'bg-rose-50',
      tagBorder: 'border-rose-200',
      tagText: 'text-rose-900',
      cardBorder: 'border-rose-100',
      sidebarBg: 'bg-rose-50/20',
      sidebarBorder: 'border-rose-100',
      previewHex: '#4c0519',
    }
  },
  {
    id: 'hedge-fund-quant',
    number: 93,
    name: 'Hedge Fund Quant',
    category: 'Legal & Finance',
    description: 'Dark terminal styling with subtle mathematical clarity for algorithmic traders.',
    layout: 'single-column',
    font: 'mono',
    colors: {
      headerBg: 'bg-black',
      headerText: 'text-white',
      headerJob: 'text-cyan-400',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-black border-cyan-600',
      sectionLine: 'border-b-2 border-cyan-600',
      tagBg: 'bg-cyan-50',
      tagBorder: 'border-cyan-300',
      tagText: 'text-cyan-950',
      cardBorder: 'border-stone-300',
      previewHex: '#0891b2',
    }
  },
  {
    id: 'risk-officer',
    number: 94,
    name: 'Chief Risk Officer',
    category: 'Legal & Finance',
    description: 'Sturdy charcoal and steel framing indicating stability and compliance rigor.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-neutral-900',
      headerText: 'text-white',
      headerJob: 'text-neutral-300',
      headerContact: 'text-neutral-300',
      sectionTitle: 'text-neutral-950 border-neutral-700',
      sectionLine: 'border-b-2 border-neutral-700',
      tagBg: 'bg-neutral-100',
      tagBorder: 'border-neutral-300',
      tagText: 'text-neutral-800',
      cardBorder: 'border-neutral-200',
      sidebarBg: 'bg-neutral-50',
      sidebarBorder: 'border-neutral-200',
      previewHex: '#262626',
    }
  },
  {
    id: 'actuary-stat',
    number: 95,
    name: 'Senior Actuary',
    category: 'Legal & Finance',
    description: 'Precise royal blue with clean statistical layout for insurance actuaries.',
    layout: 'top-banner',
    font: 'sans',
    colors: {
      headerBg: 'bg-blue-900',
      headerText: 'text-white',
      headerJob: 'text-blue-200',
      headerContact: 'text-blue-100',
      sectionTitle: 'text-blue-950 border-blue-600',
      sectionLine: 'border-b-2 border-blue-600',
      tagBg: 'bg-blue-50',
      tagBorder: 'border-blue-200',
      tagText: 'text-blue-900',
      cardBorder: 'border-blue-100',
      previewHex: '#1d4ed8',
    }
  },
  {
    id: 'patent-attorney',
    number: 96,
    name: 'Patent Attorney',
    category: 'Legal & Finance',
    description: 'Technical legal hybrid layout for intellectual property & patent specialists.',
    layout: 'timeline',
    font: 'sans',
    colors: {
      headerBg: 'bg-slate-900',
      headerText: 'text-white',
      headerJob: 'text-slate-300',
      headerContact: 'text-slate-300',
      sectionTitle: 'text-slate-900 border-slate-700',
      sectionLine: 'border-b-2 border-slate-700',
      tagBg: 'bg-slate-100',
      tagBorder: 'border-slate-300',
      tagText: 'text-slate-800',
      cardBorder: 'border-slate-200',
      accentDot: 'bg-slate-700',
      previewHex: '#334155',
    }
  },
  {
    id: 'wealth-management',
    number: 97,
    name: 'Wealth Advisory',
    category: 'Legal & Finance',
    description: 'Rich dark emerald and champagne tones for ultra-high-net-worth portfolio advisors.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-emerald-950',
      headerText: 'text-amber-100',
      headerJob: 'text-amber-300',
      headerContact: 'text-emerald-100',
      sectionTitle: 'text-emerald-950 border-amber-600',
      sectionLine: 'border-b-2 border-amber-600',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-200',
      tagText: 'text-amber-950',
      cardBorder: 'border-emerald-100',
      previewHex: '#064e3b',
    }
  },
  {
    id: 'tax-consultant',
    number: 98,
    name: 'Tax Partner',
    category: 'Legal & Finance',
    description: 'Structured column dividers for international corporate tax strategists.',
    layout: 'left-sidebar',
    font: 'sans',
    colors: {
      headerBg: 'bg-sky-950',
      headerText: 'text-white',
      headerJob: 'text-sky-200',
      headerContact: 'text-sky-100',
      sectionTitle: 'text-sky-950 border-sky-600',
      sectionLine: 'border-b-2 border-sky-600',
      tagBg: 'bg-sky-50',
      tagBorder: 'border-sky-200',
      tagText: 'text-sky-900',
      cardBorder: 'border-sky-100',
      sidebarBg: 'bg-sky-50/40',
      sidebarBorder: 'border-sky-100',
      previewHex: '#0c4a6e',
    }
  },
  {
    id: 'notary-chancery',
    number: 99,
    name: 'Chancery Notary',
    category: 'Legal & Finance',
    description: 'Historic formal legal formatting with seal-like header accents.',
    layout: 'single-column',
    font: 'serif',
    colors: {
      headerBg: 'bg-stone-900',
      headerText: 'text-amber-50',
      headerJob: 'text-stone-300',
      headerContact: 'text-stone-300',
      sectionTitle: 'text-stone-900 border-stone-600',
      sectionLine: 'border-b-2 border-stone-600',
      tagBg: 'bg-stone-100',
      tagBorder: 'border-stone-300',
      tagText: 'text-stone-900',
      cardBorder: 'border-stone-200',
      previewHex: '#292524',
    }
  },
  {
    id: 'sovereign-treasury',
    number: 100,
    name: 'Sovereign Treasury',
    category: 'Legal & Finance',
    description: 'The pinnacle 100th style: Majestic deep royal navy, gold pinstripe, and master-level typographic precision.',
    layout: 'top-banner',
    font: 'serif',
    colors: {
      headerBg: 'bg-gradient-to-r from-blue-950 via-slate-900 to-indigo-950',
      headerText: 'text-amber-200 font-bold',
      headerJob: 'text-amber-100',
      headerContact: 'text-slate-200',
      sectionTitle: 'text-blue-950 border-amber-600 font-bold',
      sectionLine: 'border-b-2 border-amber-600',
      tagBg: 'bg-amber-50',
      tagBorder: 'border-amber-300',
      tagText: 'text-amber-950',
      cardBorder: 'border-amber-200',
      previewHex: '#1e1b4b',
    }
  },
];

// Helper to lookup style by ID with fallback
export function getCVStyle(id: string): CVStyle {
  const found = CV_STYLES.find(s => s.id === id);
  if (found) return found;
  // Fallbacks for any legacy/unknown values
  if (id === 'blue') return CV_STYLES[0];
  if (id === 'black') return CV_STYLES[1];
  if (id === 'green') return CV_STYLES[2];
  return CV_STYLES[0];
}
